#!/usr/bin/env bash

FILE="input.txt"
# FILE="input_example.txt"

FORWARD=$(grep forward "$FILE" | cut -d " " -f 2 | paste -s -d"+" | bc)
DOWN=$(grep down "$FILE" | cut -d " " -f 2 | paste -s -d"+" | bc)
UP=$(grep up "$FILE" | cut -d " " -f 2 | paste -s -d"+" | bc)

POSITION=$(echo "$FORWARD * ($DOWN - $UP)" | bc)
echo "Part one: $POSITION"

# --
VERTICAL=0
AIM=0

while read -r LINE; do
  VALUE=$(echo "$LINE" | cut -d " " -f 2 )

  if [[ "$LINE" == f* ]]; then
    (( VERTICAL += (VALUE * AIM) ))
  elif [[ "$LINE" == u* ]]; then
    (( AIM -= VALUE ))
  else
    (( AIM += VALUE ))
  fi
done < "$FILE"

POSITION=$(echo "$FORWARD * $VERTICAL" | bc)
echo "Part two: $POSITION"
